# Financial Q&A 10-K — LLM Financial Question Answering:

This notebook builds a lightweight LLM-based question-answering pipeline using 50 samples from the Financial Q&A 10-K dataset.

The pipeline will:

1. Load and validate the dataset
2. Select exactly 50 valid samples
3. Generate answers using an LLM
4. Compare generated answers with reference answers
5. Evaluate and analyze the results

## 1. Setup:

In [1]:
import sys 
import pandas as pd 

print("Python:", sys.executable)
print("Pandas:", pd.__version__)

Python: /Users/yagyansh/Desktop/pwc-take-home-task/.venv/bin/python
Pandas: 3.0.5

## 2. Loading Dataset:

In [2]:
RAW_DATA_PATH = "/Users/yagyansh/Desktop/pwc-take-home-task/data/Financial-QA-10k.csv"

raw_df = pd.read_csv(RAW_DATA_PATH)

print("Shape:", raw_df.shape)
print("Columns:", raw_df.columns.tolist())

Shape: (7000, 5)
Columns: ['question', 'answer', 'context', 'ticker', 'filing']

## 3. Create the 50-Sample Evaluation Set:

I am supposed to be using only 50 samples which is why I am removing rows with missing values in the fields required for question answering.

In [3]:
raw_df.head(5)

,question,answer,context,ticker,filing
0,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,"Since our original focus on PC graphics, we ha...",NVDA,2023_10K
1,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Some of the most recent applications of GPU-po...,NVDA,2023_10K
2,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,Our invention of the GPU in 1999 defined moder...,NVDA,2023_10K
3,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"NVIDIA has a platform strategy, bringing toget...",NVDA,2023_10K
4,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,With our introduction of the CUDA programming ...,NVDA,2023_10K

In [4]:
required_columns = ["question", "context", "answer"]
valid_df = raw_df.dropna(subset=required_columns).copy()

print("Valid Rows:", len(valid_df))

Valid Rows: 6997

In [5]:
samples_50 = valid_df.head(50).copy()
print("Samples Shape:", samples_50.shape)

Samples Shape: (50, 5)

In [6]:
samples_50.head()

,question,answer,context,ticker,filing
0,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,"Since our original focus on PC graphics, we ha...",NVDA,2023_10K
1,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Some of the most recent applications of GPU-po...,NVDA,2023_10K
2,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,Our invention of the GPU in 1999 defined moder...,NVDA,2023_10K
3,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"NVIDIA has a platform strategy, bringing toget...",NVDA,2023_10K
4,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,With our introduction of the CUDA programming ...,NVDA,2023_10K

In [7]:
OUTPUT_PATH = "/Users/yagyansh/Desktop/pwc-take-home-task/data/samples_50.csv"

samples_50.to_csv(OUTPUT_PATH, index = False)
print(f"Saved samples to {OUTPUT_PATH}")

Saved samples to /Users/yagyansh/Desktop/pwc-take-home-task/data/samples_50.csv

In [8]:
check_df = pd.read_csv(OUTPUT_PATH)

print("Verified shapeL", check_df.shape)
print("Columns:", check_df.columns.tolist())

Verified shapeL (50, 5)
Columns: ['question', 'answer', 'context', 'ticker', 'filing']

## 4. Prompt Construction

The model receives the question and the supporting context. The reference answer **("answer" column)** is excluded from the prompt because it is used as ground truth for evaluation.

In [9]:
def build_prompt(question, context):
    return f"""
You are a financial question-answering assistant.

Answer the question using ONLY the information contained in the provided context.

Rules:
- Do not use external knowledge or information from your training data.
- Do not make assumptions that are not supported by the context.
- Do not invent facts or figures.
- If the context does not contain enough information to answer the question reliably,
  abstain by returning "ABSTAIN".
- Keep the answer concise and directly answer the question.

Context:
{context}

Question:
{question}

Answer:
"""

In [10]:
test_sample = samples_50.iloc[0]

prompt = build_prompt(
    test_sample["question"],
    test_sample["context"]
)

print(prompt)

You are a financial question-answering assistant.

Answer the question using ONLY the information contained in the provided context.

Rules:
- Do not use external knowledge or information from your training data.
- Do not make assumptions that are not supported by the context.
- Do not invent facts or figures.
- If the context does not contain enough information to answer the question reliably,
  abstain by returning "ABSTAIN".
- Keep the answer concise and directly answer the question.

Context:
Since our original focus on PC graphics, we have expanded to several other large and important computationally intensive fields.

Question:
What area did NVIDIA initially focus on before expanding to other computationally intensive fields?

Answer:

In [11]:
print("Question Length:", len(test_sample["question"]))
print("Context Length:", len(test_sample["context"]))
print("Reference Answer Length:", len(test_sample["answer"]))

Question Length: 99
Context Length: 128
Reference Answer Length: 40

In [12]:
print("Reference answer:")
print(test_sample["answer"])

Reference answer:
NVIDIA initially focused on PC graphics.

## 5. Model Selection:

Choosing 2 different LLM models from the OpenAI family of models especially given their recent dominance against Anthropic. Both these models will be evaluated using the same 50 examples and the same prompt structure.


- Model A: GPT-5.6 Sol (`gpt-5.6-sol`) — selected as the quality/reliability-oriented model
- Model B: GPT-5.6 Luna (`gpt-5.6-luna`) — selected as the cost-oriented model

Both Models A & B will be compared on:
- Answer correctness
- Context adherence
- Abstention behaviour
- Consistency
- Cost

The models will receive only the question and supporting context from the dataset to support them in answering the questions asked by our users.

In [13]:
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY was not found.")

print("API key loaded successfully.")

API key loaded successfully.

In [14]:
from openai import OpenAI

client = OpenAI(api_key=api_key)

print("OpenAI client created successfully.")

OpenAI client created successfully.

In [15]:
models = client.models.list()

for model in models.data:
    if any(name in model.id.lower() for name in ["gpt-5", "gpt-4.1", "gpt-4o"]):
        print(model.id)

gpt-4o
gpt-4o-2024-05-13
gpt-4o-mini-2024-07-18
gpt-4o-mini
gpt-4o-2024-08-06
gpt-4o-2024-11-20
gpt-4o-mini-search-preview-2025-03-11
gpt-4o-mini-search-preview
gpt-4o-transcribe
gpt-4o-mini-transcribe
gpt-4o-mini-tts
gpt-4.1-2025-04-14
gpt-4.1
gpt-4.1-mini-2025-04-14
gpt-4.1-mini
gpt-4.1-nano-2025-04-14
gpt-4.1-nano
gpt-4o-transcribe-diarize
gpt-5-chat-latest
gpt-5-2025-08-07
gpt-5
gpt-5-mini-2025-08-07
gpt-5-mini
gpt-5-nano-2025-08-07
gpt-5-nano
gpt-5-codex
gpt-5-pro-2025-10-06
gpt-5-pro
gpt-5-search-api
gpt-5-search-api-2025-10-14
gpt-5.1-chat-latest
gpt-5.1-2025-11-13
gpt-5.1
gpt-5.1-codex
gpt-5.1-codex-mini
gpt-5.1-codex-max
gpt-5.2-2025-12-11
gpt-5.2
gpt-5.2-pro-2025-12-11
gpt-5.2-pro
gpt-5.2-chat-latest
gpt-4o-mini-transcribe-2025-12-15
gpt-4o-mini-transcribe-2025-03-20
gpt-4o-mini-tts-2025-03-20
gpt-4o-mini-tts-2025-12-15
gpt-5.2-codex
gpt-5.3-codex
gpt-4o-search-preview
gpt-4o-search-preview-2025-03-11
gpt-5.3-chat-latest
gpt-5.4-2026-03-05
gpt-5.4-pro
gpt-5.4-pro-2026-03-05
gpt-5.4
gpt-5.4-nano-2026-03-17
gpt-5.4-nano
gpt-5.4-mini-2026-03-17
gpt-5.4-mini
gpt-5.5
gpt-5.5-2026-04-23
gpt-5.5-pro
gpt-5.5-pro-2026-04-23
gpt-5.6-sol
gpt-5.6-terra
gpt-5.6-luna

In [16]:
MODEL_A = "gpt-5.6-sol"
MODEL_B = "gpt-5.6-luna"

print("Model A:", MODEL_A)
print("Model B:", MODEL_B)

Model A: gpt-5.6-sol
Model B: gpt-5.6-luna

## 6. API Call Model Test Run:

In [17]:
test_sample = samples_50.iloc[0]

test_prompt = build_prompt(
    test_sample["question"],
    test_sample["context"]
)

print("QUESTION:")
print(test_sample["question"])

print("\nREFERENCE ANSWER:")
print(test_sample["answer"])

QUESTION:
What area did NVIDIA initially focus on before expanding to other computationally intensive fields?

REFERENCE ANSWER:
NVIDIA initially focused on PC graphics.

## Model A:

In [ ]:
response = client.responses.create(
    model=MODEL_A,
    input=test_prompt,
    reasoning={"effort": "none"} # mentioned reasoning equal to none because we are doing straightforward context-based extraction
)

model_a_answer = response.output_text

print("\nMODEL A ANSWER:")
print(model_a_answer)

MODEL A ANSWER:
PC graphics.

In [19]:
response = client.responses.create(
    model=MODEL_B,
    input=test_prompt,
    reasoning={"effort": "none"} # mentioned reasoning equal to none because we are doing straightforward context-based extraction
)

model_b_answer = response.output_text

print("\nMODEL B ANSWER:")
print(model_b_answer)

MODEL B ANSWER:
PC graphics

## 7. Generating Predictions:

In [20]:
def generate_answer(model_name, question, context):
    prompt = build_prompt(question, context)

    response = client.responses.create(
        model = model_name, 
        input = prompt,
        reasoning = {"effort": "none"}
    )

    answer = response.output_text.strip()

    return {
        "predicted_answer": answer,
        "abstained": answer.upper() == "ABSTAIN",
        "response_id": response.id
    }

In [21]:
test_result_a = generate_answer(
    MODEL_A, 
    test_sample["question"],
    test_sample["context"]
)

test_result_b = generate_answer(
    MODEL_B,
    test_sample["question"],
    test_sample["context"]
)

print("MODEL A:")
print(test_result_a)

print("MODEL B:")
print(test_result_b)

MODEL A:
{'predicted_answer': 'PC graphics.', 'abstained': False, 'response_id': 'resp_0f500545e32ba2ae006a9c880d3fbc87d2a59bfcfaf03586e5'}
MODEL B:
{'predicted_answer': 'PC graphics', 'abstained': False, 'response_id': 'resp_0b2603a895c70825006a9c880ed2a887d28509d10cdd1987ab'}

In [22]:
import time

def run_model_on_samples(model_name, samples):
    results = []

    for idx, row in samples.iterrows():
        result = generate_answer(
            model_name,
            row["question"],
            row["context"]
        )

        results.append({
            "sample_id": idx + 1,
            "question": row["question"],
            "context": row["context"],
            "reference_answer": row["answer"],
            "predicted_answer": result["predicted_answer"],
            "abstained": result["abstained"],
            "response_id": result["response_id"],
            "model": model_name
        })

        print(f"{model_name}: completed {len(results)}/{len(samples)}")

    return pd.DataFrame(results)

In [23]:
results_a = run_model_on_samples(
    MODEL_A,
    samples_50
)

gpt-5.6-sol: completed 1/50
gpt-5.6-sol: completed 2/50
gpt-5.6-sol: completed 3/50
gpt-5.6-sol: completed 4/50
gpt-5.6-sol: completed 5/50
gpt-5.6-sol: completed 6/50
gpt-5.6-sol: completed 7/50
gpt-5.6-sol: completed 8/50
gpt-5.6-sol: completed 9/50
gpt-5.6-sol: completed 10/50
gpt-5.6-sol: completed 11/50
gpt-5.6-sol: completed 12/50
gpt-5.6-sol: completed 13/50
gpt-5.6-sol: completed 14/50
gpt-5.6-sol: completed 15/50
gpt-5.6-sol: completed 16/50
gpt-5.6-sol: completed 17/50
gpt-5.6-sol: completed 18/50
gpt-5.6-sol: completed 19/50
gpt-5.6-sol: completed 20/50
gpt-5.6-sol: completed 21/50
gpt-5.6-sol: completed 22/50
gpt-5.6-sol: completed 23/50
gpt-5.6-sol: completed 24/50
gpt-5.6-sol: completed 25/50
gpt-5.6-sol: completed 26/50
gpt-5.6-sol: completed 27/50
gpt-5.6-sol: completed 28/50
gpt-5.6-sol: completed 29/50
gpt-5.6-sol: completed 30/50
gpt-5.6-sol: completed 31/50
gpt-5.6-sol: completed 32/50
gpt-5.6-sol: completed 33/50
gpt-5.6-sol: completed 34/50
gpt-5.6-sol: completed 35/50
gpt-5.6-sol: completed 36/50
gpt-5.6-sol: completed 37/50
gpt-5.6-sol: completed 38/50
gpt-5.6-sol: completed 39/50
gpt-5.6-sol: completed 40/50
gpt-5.6-sol: completed 41/50
gpt-5.6-sol: completed 42/50
gpt-5.6-sol: completed 43/50
gpt-5.6-sol: completed 44/50
gpt-5.6-sol: completed 45/50
gpt-5.6-sol: completed 46/50
gpt-5.6-sol: completed 47/50
gpt-5.6-sol: completed 48/50
gpt-5.6-sol: completed 49/50
gpt-5.6-sol: completed 50/50

In [25]:
results_b = run_model_on_samples(
    MODEL_B,
    samples_50
)

gpt-5.6-luna: completed 1/50
gpt-5.6-luna: completed 2/50
gpt-5.6-luna: completed 3/50
gpt-5.6-luna: completed 4/50
gpt-5.6-luna: completed 5/50
gpt-5.6-luna: completed 6/50
gpt-5.6-luna: completed 7/50
gpt-5.6-luna: completed 8/50
gpt-5.6-luna: completed 9/50
gpt-5.6-luna: completed 10/50
gpt-5.6-luna: completed 11/50
gpt-5.6-luna: completed 12/50
gpt-5.6-luna: completed 13/50
gpt-5.6-luna: completed 14/50
gpt-5.6-luna: completed 15/50
gpt-5.6-luna: completed 16/50
gpt-5.6-luna: completed 17/50
gpt-5.6-luna: completed 18/50
gpt-5.6-luna: completed 19/50
gpt-5.6-luna: completed 20/50
gpt-5.6-luna: completed 21/50
gpt-5.6-luna: completed 22/50
gpt-5.6-luna: completed 23/50
gpt-5.6-luna: completed 24/50
gpt-5.6-luna: completed 25/50
gpt-5.6-luna: completed 26/50
gpt-5.6-luna: completed 27/50
gpt-5.6-luna: completed 28/50
gpt-5.6-luna: completed 29/50
gpt-5.6-luna: completed 30/50
gpt-5.6-luna: completed 31/50
gpt-5.6-luna: completed 32/50
gpt-5.6-luna: completed 33/50
gpt-5.6-luna: completed 34/50
gpt-5.6-luna: completed 35/50
gpt-5.6-luna: completed 36/50
gpt-5.6-luna: completed 37/50
gpt-5.6-luna: completed 38/50
gpt-5.6-luna: completed 39/50
gpt-5.6-luna: completed 40/50
gpt-5.6-luna: completed 41/50
gpt-5.6-luna: completed 42/50
gpt-5.6-luna: completed 43/50
gpt-5.6-luna: completed 44/50
gpt-5.6-luna: completed 45/50
gpt-5.6-luna: completed 46/50
gpt-5.6-luna: completed 47/50
gpt-5.6-luna: completed 48/50
gpt-5.6-luna: completed 49/50
gpt-5.6-luna: completed 50/50

In [26]:
results_a[[
    "sample_id",
    "reference_answer",
    "predicted_answer",
    "abstained"
]].head(10)

,sample_id,reference_answer,predicted_answer,abstained
0,1,NVIDIA initially focused on PC graphics.,PC graphics.,False
1,2,Recent applications of GPU-powered deep learni...,Recent applications include recommendation sys...,False
2,3,NVIDIA invented the GPU in 1999.,NVIDIA invented the GPU in 1999.,False
3,4,NVIDIA's platform strategy brings together har...,"It integrates hardware, systems, software, alg...",False
4,5,NVIDIA's CUDA programming model opened the par...,It enables the GPU’s parallel processing capab...,False
5,6,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",False
6,7,NVIDIA and SoftBank terminated their Share Pur...,They terminated the agreement due to significa...,False
7,8,NVIDIA recorded an acquisition termination cos...,$1.35 billion.,False
8,9,The NVIDIA computing platform focuses on accel...,"The most compute-intensive workloads, includin...",False
9,10,The NVIDIA computing platform includes energy-...,The NVIDIA computing platform includes energy-...,False

In [27]:
results_a

,sample_id,question,context,reference_answer,predicted_answer,abstained,response_id,model
0,1,What area did NVIDIA initially focus on before...,"Since our original focus on PC graphics, we ha...",NVIDIA initially focused on PC graphics.,PC graphics.,False,resp_064193139907dedf006a9c884847d087d2a3d3573...,gpt-5.6-sol
1,2,What are some of the recent applications of GP...,Some of the most recent applications of GPU-po...,Recent applications of GPU-powered deep learni...,Recent applications include recommendation sys...,False,resp_0e5530428dab770f006a9c884a547c87d2bdea6c0...,gpt-5.6-sol
2,3,What significant invention did NVIDIA create i...,Our invention of the GPU in 1999 defined moder...,NVIDIA invented the GPU in 1999.,NVIDIA invented the GPU in 1999.,False,resp_0186743ca973334f006a9c884c33e087d2bf69a11...,gpt-5.6-sol
3,4,How does NVIDIA's platform strategy contribute...,"NVIDIA has a platform strategy, bringing toget...",NVIDIA's platform strategy brings together har...,"It integrates hardware, systems, software, alg...",False,resp_0bd634d092f2c27b006a9c884dbb0c87d29904dbc...,gpt-5.6-sol
4,5,What does NVIDIA's CUDA programming model enable?,With our introduction of the CUDA programming ...,NVIDIA's CUDA programming model opened the par...,It enables the GPU’s parallel processing capab...,False,resp_081c4e4462fc97ab006a9c884f1cd087d2bae2b02...,gpt-5.6-sol
5,6,What industries use NVIDIA's GPUs and software...,A rapidly growing number of enterprises and st...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",False,resp_080dc67e12527bbe006a9c88508eac87d2ac6de1e...,gpt-5.6-sol
6,7,Why did NVIDIA and SoftBank terminate their Sh...,Termination of the Arm Share Purchase Agreemen...,NVIDIA and SoftBank terminated their Share Pur...,They terminated the agreement due to significa...,False,resp_07fb1090b38ade9b006a9c8851c50887d29316321...,gpt-5.6-sol
7,8,What amount did NVIDIA record as an acquisitio...,We recorded an acquisition termination cost of...,NVIDIA recorded an acquisition termination cos...,$1.35 billion.,False,resp_0b6f12fa8e11d6f2006a9c885401f487d2a92e007...,gpt-5.6-sol
8,9,What does the NVIDIA computing platform focus ...,Data Center The NVIDIA computing platform is f...,The NVIDIA computing platform focuses on accel...,"The most compute-intensive workloads, includin...",False,resp_0de97e45ccc11fba006a9c88561bf487d2bababf2...,gpt-5.6-sol
9,10,What are the key components of the NVIDIA comp...,Data Center The NVIDIA computing platform is f...,The NVIDIA computing platform includes energy-...,The NVIDIA computing platform includes energy-...,False,resp_0fc031d32f494816006a9c8857567887d2b85d039...,gpt-5.6-sol
10,11,What is the H100 GPU designed to accelerate?,H100 is ideal for accelerating applications su...,The H100 GPU is designed to accelerate applica...,"Large language models, deep recommender system...",False,resp_0b85623f39f5a30f006a9c8858dc7087d287b8c88...,gpt-5.6-sol
11,12,What services does NVIDIA offer to enterprise ...,NVIDIA will offer enterprise customers NVIDIA ...,NVIDIA offers enterprise customers NVIDIA AI c...,NVIDIA offers enterprise customers AI cloud se...,False,resp_0e6f0cf4c520aa57006a9c885b354087d2920d501...,gpt-5.6-sol
12,13,What does the Bluefield DPU support?,The NVIDIA Bluefield DPU is supported by found...,The Bluefield DPU is supported by foundational...,"The BlueField DPU supports DOCA, enabling soft...",False,resp_0f7c4d820158a52b006a9c885c87d487d2bf18b4e...,gpt-5.6-sol
13,14,What does the NVIDIA GPU Cloud registry offer?,"We also offer the NVIDIA GPU Cloud registry, o...",The NVIDIA GPU Cloud registry offers a compreh...,"A comprehensive catalog of easy-to-use, optimi...",False,resp_08a29bac8c49ed45006a9c885e4f9087d289439e2...,gpt-5.6-sol
14,15,What are the technological features of the GeF...,"In fiscal year 2023, we introduced the GeForce...",The GeForce RTX 40 Series GPUs feature third g...,The GeForce RTX 40 Series GPUs feature the Ada...,False,resp_066051ecfe50af99006a9c885f700c87d281c4500...,gpt-5.6-sol
15,16,What generation technology does the 40 Series ...,The 40 Series features our third generation RT...,The 40 Series graphics cards feature third gen...,"Third-generation RTX technology, third-generat...",False,resp_0848eaa22c839145006a9c886117a087d293a1706...,gpt-5.6-sol
16,17,What capabilities are introduced by NVIDIA's G...,Professional Visualization We serve the Profes...,NVIDIA's GPU computing platform enhances produ...,New capabilities for critical workflows in fie...,False,resp_0d91aa8d5b06e4fc006a9c886275a887d293c2933...,gpt-5.6-sol
17,18,What kind of applications now support RTX tech...,Many leading 3D design and content creation ap...,Many leading 3D design and content creation ap...,Leading 3D design and content creation applica...,False,resp_05c4cb1d875afa13006a9c8863915087d2b333911...,gpt-5.6-sol
18,19,What are some current enterprise applications ...,"Omniverse, virtual reality, or VR, and augment...",Current enterprise applications of VR and AR t...,Current enterprise applications include virtua...,False,resp_0f6bcdd29a2760d7006a9c8864c58087d2870d946...,gpt-5.6-sol
19,20,What features does the DRIVE Software platform...,The DRIVE Software platform includes DRIVE Cha...,The DRIVE Software platform includes DRIVE Cha...,The DRIVE Software platform includes:\n\n- DRI...,False,resp_010f0c6ef3fa665f006a9c8866448087d2b847334...,gpt-5.6-sol
20,21,How does the company support multi-billion-dol...,investments in research and development: we ca...,The company supports multi-billion-dollar end ...,By using shared underlying technology with var...,False,resp_0f12b09d5edd3203006a9c8867bddc87d29984dc4...,gpt-5.6-sol
21,22,What comprehensive solutions does the company ...,"We provide a complete, end-to-end accelerated ...","The company provides a complete, end-to-end ac...",The company provides an end-to-end accelerated...,False,resp_0201fc8d92d02f2c006a9c8869476087d28618593...,gpt-5.6-sol
22,23,How does the company advance autonomous vehicl...,Advancing the leading autonomous vehicle platf...,The company provides a fully functional safety...,The company advances autonomous vehicle techno...,False,resp_0faa3c6511c98b50006a9c886aa69087d2a5959e2...,gpt-5.6-sol
23,24,What specific features are used to enhance the...,Our technologies are instrumental in driving g...,The company uses its GeForce Experience to opt...,GeForce Experience enhances consumers’ gaming ...,False,resp_00ac08239d344d40006a9c886c9c4087d2a008570...,gpt-5.6-sol
24,25,How does the company's sales and marketing str...,Sales and Marketing Our worldwide sales and ma...,The global sales and marketing teams work clos...,The company’s global sales and marketing teams...,False,resp_0ccb6a7a5e0bb03a006a9c886eb29087d2b490b4e...,gpt-5.6-sol
25,26,What is the primary role of NVIDIA's partner n...,"partner network in designing, testing, and qua...",NVIDIA's partner network is primarily involved...,"NVIDIA’s partner network helps design, test, a...",False,resp_0b50be66aac48d35006a9c8870797887d2a011088...,gpt-5.6-sol
26,27,How does NVIDIA encourage the development of s...,To encourage the development of applications o...,NVIDIA encourages the development of software ...,NVIDIA builds developer relationships by provi...,False,resp_00446c12bcc5a6c5006a9c8871ffc487d28da07ad...,gpt-5.6-sol
27,28,How does NVIDIA's product revenue typically va...,Our consumer products typically see stronger r...,NVIDIA's product revenue typically sees strong...,Consumer product revenue is typically stronger...,False,resp_054a4c80f431d71f006a9c8873e5cc87d28e80a56...,gpt-5.6-sol
28,29,What manufacturing strategy does NVIDIA employ...,We do not manufacture semiconductors used for ...,NVIDIA employs a fabless manufacturing strateg...,NVIDIA employs a fabless manufacturing strateg...,False,resp_05eb7aa158f5e4d8006a9c8876047887d288094ba...,gpt-5.6-sol
29,30,Who are NVIDIA's primary suppliers for semicon...,"We utilize suppliers, such as Taiwan Semicondu...",NVIDIA's primary suppliers for semiconductor w...,Taiwan Semiconductor Manufacturing Company Lim...,False,resp_0084432312c8602c006a9c887797b087d29207a83...,gpt-5.6-sol
30,31,What are the principal competitive factors in ...,Competition The market for our products is in...,The principal competitive factors include perf...,The principal competitive factors are performa...,False,resp_0d10593a9b8fddd6006a9c8878b27c87d295c258f...,gpt-5.6-sol
31,32,How does the text describe the changes expecte...,We believe that the principal competitive fact...,The text suggests that competition will increa...,The company expects competition to intensify f...,False,resp_063bc1a2b25a6b66006a9c887a461087d284f0ecf...,gpt-5.6-sol
32,33,What entities are identified as significant so...,A significant source of competition comes from...,Significant sources of competition include com...,Companies providing or intending to provide:\n...,False,resp_07f137135fa9ed82006a9c887be0a087d295d8235...,gpt-5.6-sol
33,34,What measures does the company rely on to prot...,Patents and Proprietary Rights We rely primari...,The company relies on a combination of patents...,"The company relies on patents, trademarks, tra...",False,resp_0fe55a71d1a6874c006a9c887d643487d2872314e...,gpt-5.6-sol
34,35,What recent regulatory changes have impacted t...,"During the third quarter of fiscal year 2023, ...","During the third quarter of fiscal year 2023, ...",The U.S. government introduced new license req...,False,resp_0911bb482f9ae389006a9c887ef30487d2b5c093f...,gpt-5.6-sol
35,36,What was the main reason for the termination o...,"In February 2022, we announced the termination...",The main reason for the termination of the Sha...,Significant regulatory challenges prevented co...,False,resp_075e2c91082381ba006a9c888063a887d284d7c49...,gpt-5.6-sol
36,37,What was the financial cost associated with th...,"In February 2022, we announced the termination...",The financial cost associated with the termina...,The termination resulted in a $1.35 billion ac...,False,resp_0e1f8ef562abe44a006a9c8882338087d2b87c3c5...,gpt-5.6-sol
37,38,What percentage of global electricity usage do...,"By the end of fiscal year 2025, our goal is to...","By the end of fiscal year 2025, NVIDIA aims to...",100%,False,resp_0960c00806a13c80006a9c88838fdc87d28278167...,gpt-5.6-sol
38,39,What new governmental requirements were announ...,"During the third quarter of fiscal year 2023, ...","During the third quarter of fiscal year 2023, ...",New license requirements for certain exports t...,False,resp_0c69e41591a003e0006a9c88849d6087d29f4cc16...,gpt-5.6-sol
39,40,What is the role of the Nominating and Corpora...,The Nominating and Corporate Governance Commit...,The role of the Nominating and Corporate Gover...,It reviews and discusses NVIDIA’s ESG-related ...,False,resp_0893c1d1fed06bcc006a9c8885ef0887d29cd277c...,gpt-5.6-sol
40,41,How many employees did the company have at the...,Human Capital Management We believe that our e...,"At the end of fiscal year 2023, the company ha...","The company had 26,196 employees in 35 countries.",False,resp_0f3817084251ad37006a9c8887a86487d28777e86...,gpt-5.6-sol
41,42,What percentage of the company's workforce hol...,Recruitment As the demand for global technical...,About 50% of the company's workforce hold adva...,About 50%.,False,resp_0898f6c2393c1251006a9c88899ce887d29485f2f...,gpt-5.6-sol
42,43,What was the overall turnover rate at the comp...,We want NVIDIA to be a place where people can ...,The overall turnover rate at the company in fi...,5.3%,False,resp_0fba185c1c51f63e006a9c888ab21c87d2a9d5538...,gpt-5.6-sol
43,44,What types of learning opportunities does the ...,Development and Retention To support employee ...,The company provides on-the-job training progr...,The company provides on-the-job learning throu...,False,resp_0d83b206a5acff24006a9c888c265487d2bf3006e...,gpt-5.6-sol
44,45,What percentage of the global workforce was fe...,"As of the end of fiscal year 2023, our global ...",19%,19%,False,resp_0a86e1356a5d083b006a9c888df30087d291463c3...,gpt-5.6-sol
45,46,What degree does Jen-Hsun Huang hold from Stan...,Jen-Hsun Huang holds a B.S.E.E. degree from Or...,M.S.E.E. degree,An M.S.E.E. degree.,False,resp_024b8b33adf24c1b006a9c888f086887d2a1cd220...,gpt-5.6-sol
46,47,What is the percentage of Black or African Ame...,"As of the end of fiscal year 2023, our global ...",6%,6%,False,resp_0c17ea64d4e7868f006a9c8890c85087d2a2242db...,gpt-5.6-sol
47,48,What position did Colette M. Kress hold before...,Colette M. Kress joined NVIDIA in 2013 as Exec...,Senior Vice President and Chief Financial Offi...,Senior Vice President and Chief Financial Offi...,False,resp_0c8ba7720242b019006a9c88922fb487d29fc35d7...,gpt-5.6-sol
48,49,What role did Debora Shoquist hold at JDS Unip...,"Prior to NVIDIA, Ms. Shoquist served from 2004...",Debora Shoquist served as the Executive Vice P...,Executive Vice President of Operations.,False,resp_05ee63c0519383c1006a9c8893c30c87d2aab364b...,gpt-5.6-sol
49,50,What degrees does Timothy S. Teter hold and fr...,Mr. Teter holds a B.S. degree in Mechanical En...,Timothy S. Teter holds a B.S. degree in Mechan...,Timothy S. Teter holds a B.S. in Mechanical En...,False,resp_025522a82d5e4877006a9c8894fbe887d2b9a89ca...,gpt-5.6-sol

In [29]:
results_b

,sample_id,question,context,reference_answer,predicted_answer,abstained,response_id,model
0,1,What area did NVIDIA initially focus on before...,"Since our original focus on PC graphics, we ha...",NVIDIA initially focused on PC graphics.,PC graphics,False,resp_0c7db54a1506b55d006a9c88a7dcb887d28116ca5...,gpt-5.6-luna
1,2,What are some of the recent applications of GP...,Some of the most recent applications of GPU-po...,Recent applications of GPU-powered deep learni...,"Recommendation systems, large language models,...",False,resp_0039eb8509214da7006a9c88a9190c87d2998aa29...,gpt-5.6-luna
2,3,What significant invention did NVIDIA create i...,Our invention of the GPU in 1999 defined moder...,NVIDIA invented the GPU in 1999.,The GPU (graphics processing unit).,False,resp_02a02537b7264faf006a9c88aa5d9487d2a2356d6...,gpt-5.6-luna
3,4,How does NVIDIA's platform strategy contribute...,"NVIDIA has a platform strategy, bringing toget...",NVIDIA's platform strategy brings together har...,"It brings together hardware, systems, software...",False,resp_01208a92bd3eaf10006a9c88ab474887d28b2579f...,gpt-5.6-luna
4,5,What does NVIDIA's CUDA programming model enable?,With our introduction of the CUDA programming ...,NVIDIA's CUDA programming model opened the par...,It enables general-purpose computing using the...,False,resp_09799a7913e30515006a9c88ac64b087d2a53a23b...,gpt-5.6-luna
5,6,What industries use NVIDIA's GPUs and software...,A rapidly growing number of enterprises and st...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",False,resp_0bb6abd7c82017c2006a9c88adb01887d29dc0640...,gpt-5.6-luna
6,7,Why did NVIDIA and SoftBank terminate their Sh...,Termination of the Arm Share Purchase Agreemen...,NVIDIA and SoftBank terminated their Share Pur...,They terminated the agreement because signific...,False,resp_037a52475abbfa4b006a9c88aea67887d2a708507...,gpt-5.6-luna
7,8,What amount did NVIDIA record as an acquisitio...,We recorded an acquisition termination cost of...,NVIDIA recorded an acquisition termination cos...,$1.35 billion.,False,resp_09bd273e5cd0eeaf006a9c88afe4f887d2aa3836f...,gpt-5.6-luna
8,9,What does the NVIDIA computing platform focus ...,Data Center The NVIDIA computing platform is f...,The NVIDIA computing platform focuses on accel...,The NVIDIA computing platform focuses on accel...,False,resp_0f8809f0396c00cd006a9c88b14c3c87d2b688183...,gpt-5.6-luna
9,10,What are the key components of the NVIDIA comp...,Data Center The NVIDIA computing platform is f...,The NVIDIA computing platform includes energy-...,"Energy-efficient GPUs, data processing units (...",False,resp_02fa5b427a428223006a9c88b26ca887d29811be9...,gpt-5.6-luna
10,11,What is the H100 GPU designed to accelerate?,H100 is ideal for accelerating applications su...,The H100 GPU is designed to accelerate applica...,"Large language models, deep recommender system...",False,resp_00862594202f4896006a9c88b3992087d2841f595...,gpt-5.6-luna
11,12,What services does NVIDIA offer to enterprise ...,NVIDIA will offer enterprise customers NVIDIA ...,NVIDIA offers enterprise customers NVIDIA AI c...,NVIDIA offers enterprise customers NVIDIA AI c...,False,resp_054c9fe2f191340c006a9c88b4775087d2b142480...,gpt-5.6-luna
12,13,What does the Bluefield DPU support?,The NVIDIA Bluefield DPU is supported by found...,The Bluefield DPU is supported by foundational...,"The BlueField DPU supports DOCA software, enab...",False,resp_03377dacbc8d7d0a006a9c88b72fbc87d298fa3e6...,gpt-5.6-luna
13,14,What does the NVIDIA GPU Cloud registry offer?,"We also offer the NVIDIA GPU Cloud registry, o...",The NVIDIA GPU Cloud registry offers a compreh...,"A comprehensive catalog of easy-to-use, optimi...",False,resp_0f398ab20b4941c4006a9c88b86ffc87d28edbc44...,gpt-5.6-luna
14,15,What are the technological features of the GeF...,"In fiscal year 2023, we introduced the GeForce...",The GeForce RTX 40 Series GPUs feature third g...,The GeForce RTX 40 Series features the Ada Lov...,False,resp_0bb95fe488a77a3c006a9c88b953f487d2ac6f2b1...,gpt-5.6-luna
15,16,What generation technology does the 40 Series ...,The 40 Series features our third generation RT...,The 40 Series graphics cards feature third gen...,Third-generation RTX technology.,False,resp_0a5e889582dfc01f006a9c88ba7b1c87d297ec51f...,gpt-5.6-luna
16,17,What capabilities are introduced by NVIDIA's G...,Professional Visualization We serve the Profes...,NVIDIA's GPU computing platform enhances produ...,New capabilities for critical workflows in fie...,False,resp_0a99d4b8a37c2b81006a9c88bb824c87d2810a403...,gpt-5.6-luna
17,18,What kind of applications now support RTX tech...,Many leading 3D design and content creation ap...,Many leading 3D design and content creation ap...,Many leading 3D design and content creation ap...,False,resp_0fd639aae6ae8cff006a9c88bc58e887d2983e8ba...,gpt-5.6-luna
18,19,What are some current enterprise applications ...,"Omniverse, virtual reality, or VR, and augment...",Current enterprise applications of VR and AR t...,"Virtual car showrooms, surgical training, arch...",False,resp_0f5ceeb1f56a8cf1006a9c88bde2cc87d292aa430...,gpt-5.6-luna
19,20,What features does the DRIVE Software platform...,The DRIVE Software platform includes DRIVE Cha...,The DRIVE Software platform includes DRIVE Cha...,The DRIVE Software platform includes:\n\n- DRI...,False,resp_062d4d2c6972361b006a9c88bee39c87d29183193...,gpt-5.6-luna
20,21,How does the company support multi-billion-dol...,investments in research and development: we ca...,The company supports multi-billion-dollar end ...,By using shared underlying technology across s...,False,resp_0449be343f9917cf006a9c88c0368087d2a3669a8...,gpt-5.6-luna
21,22,What comprehensive solutions does the company ...,"We provide a complete, end-to-end accelerated ...","The company provides a complete, end-to-end ac...","The company provides a complete, end-to-end ac...",False,resp_099568cdd6dd6d91006a9c88c16d9c87d29017100...,gpt-5.6-luna
22,23,How does the company advance autonomous vehicl...,Advancing the leading autonomous vehicle platf...,The company provides a fully functional safety...,The company advances autonomous vehicle techno...,False,resp_0a73a623f750b3d0006a9c88c2e60087d29ebab36...,gpt-5.6-luna
23,24,What specific features are used to enhance the...,Our technologies are instrumental in driving g...,The company uses its GeForce Experience to opt...,GeForce Experience optimizes PC settings and e...,False,resp_0426b602782a8879006a9c88c456f887d290a6a1f...,gpt-5.6-luna
24,25,How does the company's sales and marketing str...,Sales and Marketing Our worldwide sales and ma...,The global sales and marketing teams work clos...,The strategy supports technology distribution ...,False,resp_0af7d72e04c047e5006a9c88c56c5887d2a9b14c5...,gpt-5.6-luna
25,26,What is the primary role of NVIDIA's partner n...,"partner network in designing, testing, and qua...",NVIDIA's partner network is primarily involved...,"Designing, testing, and qualifying system desi...",False,resp_00ef9864d223ddf6006a9c88c6c14087d2a9cba60...,gpt-5.6-luna
26,27,How does NVIDIA encourage the development of s...,To encourage the development of applications o...,NVIDIA encourages the development of software ...,NVIDIA encourages development by making its pr...,False,resp_09da723f816598a3006a9c88c7c58087d2bded4dd...,gpt-5.6-luna
27,28,How does NVIDIA's product revenue typically va...,Our consumer products typically see stronger r...,NVIDIA's product revenue typically sees strong...,NVIDIA’s consumer product revenue is typically...,False,resp_0d64878547ed1fa4006a9c88c94e5487d29acb2ec...,gpt-5.6-luna
28,29,What manufacturing strategy does NVIDIA employ...,We do not manufacture semiconductors used for ...,NVIDIA employs a fabless manufacturing strateg...,NVIDIA employs a fabless manufacturing strateg...,False,resp_06aa7a41edc07c4c006a9c88cab96887d28284b98...,gpt-5.6-luna
29,30,Who are NVIDIA's primary suppliers for semicon...,"We utilize suppliers, such as Taiwan Semicondu...",NVIDIA's primary suppliers for semiconductor w...,Taiwan Semiconductor Manufacturing Company Lim...,False,resp_0c2d9dc0f690471d006a9c88cbdb0087d2970c963...,gpt-5.6-luna
30,31,What are the principal competitive factors in ...,Competition The market for our products is in...,The principal competitive factors include perf...,The principal competitive factors are performa...,False,resp_0eb4fad5c50e5192006a9c88ccd88087d2a98917a...,gpt-5.6-luna
31,32,How does the text describe the changes expecte...,We believe that the principal competitive fact...,The text suggests that competition will increa...,Competition is expected to increase from exist...,False,resp_07b32451282c3746006a9c88cdd00487d29f8e544...,gpt-5.6-luna
32,33,What entities are identified as significant so...,A significant source of competition comes from...,Significant sources of competition include com...,Companies providing or intending to provide GP...,False,resp_04172e42868b7907006a9c88cf48ec87d2a3d779c...,gpt-5.6-luna
33,34,What measures does the company rely on to prot...,Patents and Proprietary Rights We rely primari...,The company relies on a combination of patents...,"The company relies on patents, trademarks, tra...",False,resp_011aa8156cbec8c0006a9c88d1468c87d2816562a...,gpt-5.6-luna
34,35,What recent regulatory changes have impacted t...,"During the third quarter of fiscal year 2023, ...","During the third quarter of fiscal year 2023, ...","During Q3 fiscal 2023, the U.S. government int...",False,resp_00e489e12969f336006a9c88d232a087d282c68c4...,gpt-5.6-luna
35,36,What was the main reason for the termination o...,"In February 2022, we announced the termination...",The main reason for the termination of the Sha...,Significant regulatory challenges preventing c...,False,resp_0c704f1af182822b006a9c88d3427887d28f2ff13...,gpt-5.6-luna
36,37,What was the financial cost associated with th...,"In February 2022, we announced the termination...",The financial cost associated with the termina...,$1.35 billion.,False,resp_0c7270df10c0c667006a9c88d451c087d2b3e41d1...,gpt-5.6-luna
37,38,What percentage of global electricity usage do...,"By the end of fiscal year 2025, our goal is to...","By the end of fiscal year 2025, NVIDIA aims to...",100%,False,resp_0e0ac58b0effdfc4006a9c88d523a487d289c552a...,gpt-5.6-luna
38,39,What new governmental requirements were announ...,"During the third quarter of fiscal year 2023, ...","During the third quarter of fiscal year 2023, ...",New U.S. government license requirements affec...,False,resp_06b69aa0a4b5f018006a9c88d5d8f087d28cc20a0...,gpt-5.6-luna
39,40,What is the role of the Nominating and Corpora...,The Nominating and Corporate Governance Commit...,The role of the Nominating and Corporate Gover...,The Nominating and Corporate Governance Commit...,False,resp_077ab707028f3f74006a9c88d6eeac87d29b91816...,gpt-5.6-luna
40,41,How many employees did the company have at the...,Human Capital Management We believe that our e...,"At the end of fiscal year 2023, the company ha...","26,196 employees in 35 countries.",False,resp_0135fbb7efbaea4f006a9c88d8015087d2bda65a9...,gpt-5.6-luna
41,42,What percentage of the company's workforce hol...,Recruitment As the demand for global technical...,About 50% of the company's workforce hold adva...,50%,False,resp_03561e2da73b2c0d006a9c88d8fee487d299c4a87...,gpt-5.6-luna
42,43,What was the overall turnover rate at the comp...,We want NVIDIA to be a place where people can ...,The overall turnover rate at the company in fi...,5.3%,False,resp_0993be757de3b4e8006a9c88d9dbb487d28551b2a...,gpt-5.6-luna
43,44,What types of learning opportunities does the ...,Development and Retention To support employee ...,The company provides on-the-job training progr...,"Training programs, one-on-one coaching, ongoin...",False,resp_0f04f8be143b49d4006a9c88dab66887d2a90c9db...,gpt-5.6-luna
44,45,What percentage of the global workforce was fe...,"As of the end of fiscal year 2023, our global ...",19%,19%,False,resp_02e243496653db55006a9c88dc240487d28f1c0ab...,gpt-5.6-luna
45,46,What degree does Jen-Hsun Huang hold from Stan...,Jen-Hsun Huang holds a B.S.E.E. degree from Or...,M.S.E.E. degree,Jen-Hsun Huang holds an M.S.E.E. degree from S...,False,resp_0a10867c6e88d9f0006a9c88dd02c087d2a8e0346...,gpt-5.6-luna
46,47,What is the percentage of Black or African Ame...,"As of the end of fiscal year 2023, our global ...",6%,6%,False,resp_02b112bb102b538b006a9c88de308c87d2bff4e91...,gpt-5.6-luna
47,48,What position did Colette M. Kress hold before...,Colette M. Kress joined NVIDIA in 2013 as Exec...,Senior Vice President and Chief Financial Offi...,Senior Vice President and Chief Financial Offi...,False,resp_0e36825791badbc6006a9c88deeb1887d280beae9...,gpt-5.6-luna
48,49,What role did Debora Shoquist hold at JDS Unip...,"Prior to NVIDIA, Ms. Shoquist served from 2004...",Debora Shoquist served as the Executive Vice P...,Executive Vice President of Operations.,False,resp_0b074458414f8097006a9c88dfeae487d2826a12e...,gpt-5.6-luna
49,50,What degrees does Timothy S. Teter hold and fr...,Mr. Teter holds a B.S. degree in Mechanical En...,Timothy S. Teter holds a B.S. degree in Mechan...,Timothy S. Teter holds a B.S. in Mechanical En...,False,resp_047edc027067f6ee006a9c88e0bd4c87d2be5065c...,gpt-5.6-luna

## 8. Evaluation:

In [30]:
import re

def normalize_text(text):
    if text is None:
        return ""

    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\w\s.%$-]", "", text)

    return text

In [31]:
def exact_match(predicted, reference):
    return normalize_text(predicted) == normalize_text(reference)

In [32]:
results_a["exact_match"] = results_a.apply(
    lambda row: exact_match(
        row["predicted_answer"],
        row["reference_answer"]
    ),
    axis=1
)

results_b["exact_match"] = results_b.apply(
    lambda row: exact_match(
        row["predicted_answer"],
        row["reference_answer"]
    ),
    axis=1
)

In [33]:
print("Model A exact matches:", results_a["exact_match"].sum())
print("Model B exact matches:", results_b["exact_match"].sum())

Model A exact matches: 4
Model B exact matches: 3

## 9. LLM-AS-A-Judge:

In [34]:
def build_evaluation_prompt(question, context, reference_answer, predicted_answer):
    return f"""

You are evaluating a financial question-answering system.

Your task is to determine whether the predicted answer is correct based ONLY
on the provided question, context, and reference answer.

Evaluate the predicted answer using these rules:

- CORRECT: The prediction conveys the same substantive answer as the reference
  and is supported by the context.
- INCORRECT: The prediction contains a materially wrong answer, unsupported
  information, or contradicts the reference/context.
- ABSTAINED: The prediction explicitly says ABSTAIN or indicates that there
  is insufficient information.

Do not use external knowledge or any form of tools like MCP or RAG.

Question:
{question}

Context:
{context}

Reference answer:
{reference_answer}

Predicted answer:
{predicted_answer}

Return exactly one label:
CORRECT
INCORRECT
ABSTAINED
"""

In [39]:
JUDGE_MODEL = "gpt-4o-mini"

In [41]:
evaluation_sample = results_a.iloc[0]

evaluation_prompt = build_evaluation_prompt(
    evaluation_sample["question"],
    evaluation_sample["context"],
    evaluation_sample["reference_answer"],
    evaluation_sample["predicted_answer"]
)

judge_response = client.responses.create(
    model=JUDGE_MODEL,
    input=evaluation_prompt
)

judge_result = judge_response.output_text.strip()

print("Judge result:", judge_result)

Judge result: CORRECT

## 9. Semantic Evaluation:

In [42]:
def evaluate_prediction(
    question,
    context,
    reference_answer,
    predicted_answer
):
    evaluation_prompt = build_evaluation_prompt(
        question,
        context,
        reference_answer,
        predicted_answer
    )

    response = client.responses.create(
        model=JUDGE_MODEL,
        input=evaluation_prompt
    )

    result = response.output_text.strip().upper()

    # Keep only valid labels
    if result not in {"CORRECT", "INCORRECT", "ABSTAINED"}:
        result = "UNKNOWN"

    return result

In [44]:
test_eval_a = evaluate_prediction(
    results_a.iloc[0]["question"],
    results_a.iloc[0]["context"],
    results_a.iloc[0]["reference_answer"],
    results_a.iloc[0]["predicted_answer"]
)

print("Model A evaluation:", test_eval_a)

Model A evaluation: CORRECT

In [45]:
results_a["evaluation"] = results_a.apply(
    lambda row: evaluate_prediction(
        row["question"],
        row["context"],
        row["reference_answer"],
        row["predicted_answer"]
    ),
    axis=1
)

In [46]:
results_a["evaluation"].value_counts()

evaluation
CORRECT      49
INCORRECT     1
Name: count, dtype: int64

In [47]:
results_b["evaluation"] = results_b.apply(
    lambda row: evaluate_prediction(
        row["question"],
        row["context"],
        row["reference_answer"],
        row["predicted_answer"]
    ),
    axis=1
)

In [48]:
results_b["evaluation"].value_counts()

evaluation
CORRECT      49
INCORRECT     1
Name: count, dtype: int64

In [49]:
def calculate_metrics(results):
    total = len(results)

    correct = (results["evaluation"] == "CORRECT").sum()
    incorrect = (results["evaluation"] == "INCORRECT").sum()
    abstained = (results["evaluation"] == "ABSTAINED").sum()

    answered = total - abstained

    accuracy = correct / total
    answer_accuracy = correct / answered if answered > 0 else 0
    abstention_rate = abstained / total
    coverage = answered / total

    return {
        "total": total,
        "correct": correct,
        "incorrect": incorrect,
        "abstained": abstained,
        "accuracy": accuracy,
        "answer_accuracy": answer_accuracy,
        "abstention_rate": abstention_rate,
        "coverage": coverage
    }

In [50]:
metrics_a = calculate_metrics(results_a)
metrics_b = calculate_metrics(results_b)

metrics_a, metrics_b

({'total': 50,
  'correct': np.int64(49),
  'incorrect': np.int64(1),
  'abstained': np.int64(0),
  'accuracy': np.float64(0.98),
  'answer_accuracy': np.float64(0.98),
  'abstention_rate': np.float64(0.0),
  'coverage': np.float64(1.0)},
 {'total': 50,
  'correct': np.int64(49),
  'incorrect': np.int64(1),
  'abstained': np.int64(0),
  'accuracy': np.float64(0.98),
  'answer_accuracy': np.float64(0.98),
  'abstention_rate': np.float64(0.0),
  'coverage': np.float64(1.0)})

In [51]:
comparison = pd.DataFrame([
    {
        "Model": MODEL_A,
        **metrics_a
    },
    {
        "Model": MODEL_B,
        **metrics_b
    }
])

comparison

,Model,total,correct,incorrect,abstained,accuracy,answer_accuracy,abstention_rate,coverage
0,gpt-5.6-sol,50,49,1,0,0.98,0.98,0.0,1.0
1,gpt-5.6-luna,50,49,1,0,0.98,0.98,0.0,1.0

In [52]:
comparison_display = comparison.copy()

for column in [
    "accuracy",
    "answer_accuracy",
    "abstention_rate",
    "coverage"
]:
    comparison_display[column] = (
        comparison_display[column] * 100
    ).round(1)

comparison_display

,Model,total,correct,incorrect,abstained,accuracy,answer_accuracy,abstention_rate,coverage
0,gpt-5.6-sol,50,49,1,0,98.0,98.0,0.0,100.0
1,gpt-5.6-luna,50,49,1,0,98.0,98.0,0.0,100.0

In [53]:
incorrect_a = results_a[
    results_a["evaluation"] == "INCORRECT"
][[
    "sample_id",
    "question",
    "context",
    "reference_answer",
    "predicted_answer"
]]

incorrect_a

,sample_id,question,context,reference_answer,predicted_answer
5,6,What industries use NVIDIA's GPUs and software...,A rapidly growing number of enterprises and st...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services..."

In [56]:
incorrect_b = results_b[
    results_b["evaluation"] == "INCORRECT"
][[
    "sample_id",
    "question",
    "context",
    "reference_answer",
    "predicted_answer"
]]

incorrect_b

,sample_id,question,context,reference_answer,predicted_answer
15,16,What generation technology does the 40 Series ...,The 40 Series features our third generation RT...,The 40 Series graphics cards feature third gen...,Third-generation RTX technology.

In [55]:
samples_50.head()

,question,answer,context,ticker,filing
0,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,"Since our original focus on PC graphics, we ha...",NVDA,2023_10K
1,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Some of the most recent applications of GPU-po...,NVDA,2023_10K
2,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,Our invention of the GPU in 1999 defined moder...,NVDA,2023_10K
3,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"NVIDIA has a platform strategy, bringing toget...",NVDA,2023_10K
4,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,With our introduction of the CUDA programming ...,NVDA,2023_10K

In [57]:
print("Model A incorrect sample IDs:")
print(incorrect_a["sample_id"].tolist())

print("\nModel B incorrect sample IDs:")
print(incorrect_b["sample_id"].tolist())

Model A incorrect sample IDs:
[6]

Model B incorrect sample IDs:
[16]

In [58]:
agreement = (
    results_a["predicted_answer"].apply(normalize_text)
    ==
    results_b["predicted_answer"].apply(normalize_text)
)

print("Exact normalized agreement:", agreement.sum(), "/", len(agreement))
print("Agreement rate:", agreement.mean() * 100, "%")

Exact normalized agreement: 14 / 50
Agreement rate: 28.000000000000004 %

## 10. HITL Workflow:

In [59]:
review_df = results_a[
    [
        "sample_id",
        "question",
        "reference_answer",
        "predicted_answer",
        "evaluation"
    ]
].merge(
    results_b[
        [
            "sample_id",
            "predicted_answer",
            "evaluation"
        ]
    ],
    on="sample_id",
    suffixes=("_sol", "_luna")
)

# Show cases where either model was flagged by the LLM judge
flagged_cases = review_df[
    (review_df["evaluation_sol"].isin(["INCORRECT", "ABSTAINED"])) |
    (review_df["evaluation_luna"].isin(["INCORRECT", "ABSTAINED"]))
]

print("Flagged cases:", len(flagged_cases))

flagged_cases

Flagged cases: 2

,sample_id,question,reference_answer,predicted_answer_sol,evaluation_sol,predicted_answer_luna,evaluation_luna
5,6,What industries use NVIDIA's GPUs and software...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",INCORRECT,"Transportation, healthcare, financial services...",CORRECT
15,16,What generation technology does the 40 Series ...,The 40 Series graphics cards feature third gen...,"Third-generation RTX technology, third-generat...",CORRECT,Third-generation RTX technology.,INCORRECT

In [60]:
manual_review = flagged_cases[
    [
        "sample_id",
        "question",
        "reference_answer",
        "predicted_answer_sol",
        "evaluation_sol",
        "predicted_answer_luna",
        "evaluation_luna"
    ]
].copy()

manual_review

,sample_id,question,reference_answer,predicted_answer_sol,evaluation_sol,predicted_answer_luna,evaluation_luna
5,6,What industries use NVIDIA's GPUs and software...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",INCORRECT,"Transportation, healthcare, financial services...",CORRECT
15,16,What generation technology does the 40 Series ...,The 40 Series graphics cards feature third gen...,"Third-generation RTX technology, third-generat...",CORRECT,Third-generation RTX technology.,INCORRECT

In [61]:
manual_review.loc[
    manual_review["sample_id"] == 37,
    "evaluation_sol"
] = "CORRECT"

manual_review.loc[
    manual_review["sample_id"] == 37,
    "evaluation_luna"
] = "CORRECT"

In [62]:
for _, row in manual_review.iterrows():
    sample_id = row["sample_id"]

    results_a.loc[
        results_a["sample_id"] == sample_id,
        "final_evaluation"
    ] = row["evaluation_sol"]

    results_b.loc[
        results_b["sample_id"] == sample_id,
        "final_evaluation"
    ] = row["evaluation_luna"]

In [63]:
results_a["final_evaluation"] = results_a["evaluation"]
results_b["final_evaluation"] = results_b["evaluation"]

In [ ]:
results_a["final_evaluation"] = results_a["evaluation"]
results_b["final_evaluation"] = results_b["evaluation"]

# Apply human-reviewed corrections
for _, row in manual_review.iterrows():
    sample_id = row["sample_id"]

    results_a.loc[
        results_a["sample_id"] == sample_id,
        "final_evaluation"
    ] = row["evaluation_sol"]

    results_b.loc[
        results_b["sample_id"] == sample_id,
        "final_evaluation"
    ] = row["evaluation_luna"]

In [65]:
def calculate_final_metrics(results):
    total = len(results)

    correct = (results["final_evaluation"] == "CORRECT").sum()
    incorrect = (results["final_evaluation"] == "INCORRECT").sum()
    abstained = (results["final_evaluation"] == "ABSTAINED").sum()

    answered = correct + incorrect

    accuracy = correct / total if total else 0
    answer_accuracy = correct / answered if answered else 0
    abstention_rate = abstained / total if total else 0
    coverage = answered / total if total else 0

    return {
        "total": total,
        "correct": correct,
        "incorrect": incorrect,
        "abstained": abstained,
        "accuracy": accuracy,
        "answer_accuracy": answer_accuracy,
        "abstention_rate": abstention_rate,
        "coverage": coverage
    }

In [66]:
metrics_a_final = calculate_final_metrics(results_a)
metrics_b_final = calculate_final_metrics(results_b)

final_comparison = pd.DataFrame([
    {
        "Model": MODEL_A,
        **metrics_a_final
    },
    {
        "Model": MODEL_B,
        **metrics_b_final
    }
])

final_comparison

,Model,total,correct,incorrect,abstained,accuracy,answer_accuracy,abstention_rate,coverage
0,gpt-5.6-sol,50,49,1,0,0.98,0.98,0.0,1.0
1,gpt-5.6-luna,50,49,1,0,0.98,0.98,0.0,1.0

In [67]:
final_comparison_display = final_comparison.copy()

for column in [
    "accuracy",
    "answer_accuracy",
    "abstention_rate",
    "coverage"
]:
    final_comparison_display[column] = (
        final_comparison_display[column] * 100
    ).round(1)

final_comparison_display

,Model,total,correct,incorrect,abstained,accuracy,answer_accuracy,abstention_rate,coverage
0,gpt-5.6-sol,50,49,1,0,98.0,98.0,0.0,100.0
1,gpt-5.6-luna,50,49,1,0,98.0,98.0,0.0,100.0

In [68]:
print("Model A actual abstentions:",
      results_a["abstained"].sum())

print("Model B actual abstentions:",
      results_b["abstained"].sum())

Model A actual abstentions: 0
Model B actual abstentions: 0

In [72]:
summary = pd.DataFrame({
    "Metric": [
        "Total samples",
        "Correct",
        "Incorrect",
        "Abstained",
        "Accuracy",
        "Answer accuracy",
        "Abstention rate",
        "Coverage"
    ],
    MODEL_A: [
        metrics_a_final["total"],
        metrics_a_final["correct"],
        metrics_a_final["incorrect"],
        metrics_a_final["abstained"],
        f"{metrics_a_final['accuracy'] * 100:.1f}%",
        f"{metrics_a_final['answer_accuracy'] * 100:.1f}%",
        f"{metrics_a_final['abstention_rate'] * 100:.1f}%",
        f"{metrics_a_final['coverage'] * 100:.1f}%"
    ],
    MODEL_B: [
        metrics_b_final["total"],
        metrics_b_final["correct"],
        metrics_b_final["incorrect"],
        metrics_b_final["abstained"],
        f"{metrics_b_final['accuracy'] * 100:.1f}%",
        f"{metrics_b_final['answer_accuracy'] * 100:.1f}%",
        f"{metrics_b_final['abstention_rate'] * 100:.1f}%",
        f"{metrics_b_final['coverage'] * 100:.1f}%"
    ]
})

summary

            Metric gpt-5.6-sol gpt-5.6-luna
0    Total samples          50           50
1          Correct          49           49
2        Incorrect           1            1
3        Abstained           0            0
4         Accuracy       98.0%        98.0%
5  Answer accuracy       98.0%        98.0%
6  Abstention rate        0.0%         0.0%
7         Coverage      100.0%       100.0%

In [73]:
pip install tiktoken

Collecting tiktoken
  Downloading tiktoken-0.14.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.7 kB)
Collecting regex (from tiktoken)
  Downloading regex-2026.9.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: requests in /Users/yagyansh/Desktop/pwc-take-home-task/.venv/lib/python3.12/site-packages (from tiktoken) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/yagyansh/Desktop/pwc-take-home-task/.venv/lib/python3.12/site-packages (from requests->tiktoken) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/yagyansh/Desktop/pwc-take-home-task/.venv/lib/python3.12/site-packages (from requests->tiktoken) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/yagyansh/Desktop/pwc-take-home-task/.venv/lib/python3.12/site-packages (from requests->tiktoken) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/yagyansh/Desktop/pwc-take-home-task/.venv/lib/python3.12/site-packages (from requests->tiktoken) (2026.7.22)
Downloading tiktoken-0.14.0-cp312-cp312-macosx_11_0_arm64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 18.3 MB/s  0:00:00
Downloading regex-2026.9.3-cp312-cp312-macosx_11_0_arm64.whl (292 kB)
Installing collected packages: regex, tiktoken
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [tiktoken]
Successfully installed regex-2026.9.3 tiktoken-0.14.0
Note: you may need to restart the kernel to use updated packages.

In [74]:
import tiktoken

In [75]:
encoding = tiktoken.get_encoding("o200k_base")

def count_tokens(text):
    return len(encoding.encode(str(text)))

In [76]:
def estimate_usage(results):
    input_tokens = []
    output_tokens = []

    for _, row in results.iterrows():
        prompt = build_prompt(
            row["question"],
            row["context"]
        )

        input_tokens.append(count_tokens(prompt))
        output_tokens.append(
            count_tokens(row["predicted_answer"])
        )

    results = results.copy()
    results["estimated_input_tokens"] = input_tokens
    results["estimated_output_tokens"] = output_tokens

    return results

In [77]:
results_a = estimate_usage(results_a)
results_b = estimate_usage(results_b)

In [78]:
print("Model A input tokens:",
      results_a["estimated_input_tokens"].sum())

print("Model A output tokens:",
      results_a["estimated_output_tokens"].sum())

print("Model B input tokens:",
      results_b["estimated_input_tokens"].sum())

print("Model B output tokens:",
      results_b["estimated_output_tokens"].sum())

Model A input tokens: 8759
Model A output tokens: 1146
Model B input tokens: 8759
Model B output tokens: 1120

In [79]:
PRICING_PER_1M = {
    MODEL_A: {
        "input": 4.00,
        "output": 20.00
    },
    MODEL_B: {
        "input": 0.20,
        "output": 1.20
    }
}

In [80]:
def calculate_cost(results, model_name):
    input_cost = (
        results["estimated_input_tokens"].sum()
        / 1_000_000
        * PRICING_PER_1M[model_name]["input"]
    )

    output_cost = (
        results["estimated_output_tokens"].sum()
        / 1_000_000
        * PRICING_PER_1M[model_name]["output"]
    )

    return {
        "model": model_name,
        "input_tokens": results["estimated_input_tokens"].sum(),
        "output_tokens": results["estimated_output_tokens"].sum(),
        "input_cost": input_cost,
        "output_cost": output_cost,
        "total_cost": input_cost + output_cost
    }

In [81]:
cost_a = calculate_cost(results_a, MODEL_A)
cost_b = calculate_cost(results_b, MODEL_B)

cost_comparison = pd.DataFrame([
    cost_a,
    cost_b
])

cost_comparison

,model,input_tokens,output_tokens,input_cost,output_cost,total_cost
0,gpt-5.6-sol,8759,1146,0.035036,0.022920,0.057956
1,gpt-5.6-luna,8759,1120,0.001752,0.001344,0.003096

In [82]:
error_analysis = review_df.copy()

error_analysis[
    [
        "sample_id",
        "question",
        "reference_answer",
        "predicted_answer_sol",
        "evaluation_sol",
        "predicted_answer_luna",
        "evaluation_luna"
    ]
]

,sample_id,question,reference_answer,predicted_answer_sol,evaluation_sol,predicted_answer_luna,evaluation_luna
0,1,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,PC graphics.,CORRECT,PC graphics,CORRECT
1,2,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Recent applications include recommendation sys...,CORRECT,"Recommendation systems, large language models,...",CORRECT
2,3,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,NVIDIA invented the GPU in 1999.,CORRECT,The GPU (graphics processing unit).,CORRECT
3,4,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"It integrates hardware, systems, software, alg...",CORRECT,"It brings together hardware, systems, software...",CORRECT
4,5,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,It enables the GPU’s parallel processing capab...,CORRECT,It enables general-purpose computing using the...,CORRECT
5,6,What industries use NVIDIA's GPUs and software...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",INCORRECT,"Transportation, healthcare, financial services...",CORRECT
6,7,Why did NVIDIA and SoftBank terminate their Sh...,NVIDIA and SoftBank terminated their Share Pur...,They terminated the agreement due to significa...,CORRECT,They terminated the agreement because signific...,CORRECT
7,8,What amount did NVIDIA record as an acquisitio...,NVIDIA recorded an acquisition termination cos...,$1.35 billion.,CORRECT,$1.35 billion.,CORRECT
8,9,What does the NVIDIA computing platform focus ...,The NVIDIA computing platform focuses on accel...,"The most compute-intensive workloads, includin...",CORRECT,The NVIDIA computing platform focuses on accel...,CORRECT
9,10,What are the key components of the NVIDIA comp...,The NVIDIA computing platform includes energy-...,The NVIDIA computing platform includes energy-...,CORRECT,"Energy-efficient GPUs, data processing units (...",CORRECT
10,11,What is the H100 GPU designed to accelerate?,The H100 GPU is designed to accelerate applica...,"Large language models, deep recommender system...",CORRECT,"Large language models, deep recommender system...",CORRECT
11,12,What services does NVIDIA offer to enterprise ...,NVIDIA offers enterprise customers NVIDIA AI c...,NVIDIA offers enterprise customers AI cloud se...,CORRECT,NVIDIA offers enterprise customers NVIDIA AI c...,CORRECT
12,13,What does the Bluefield DPU support?,The Bluefield DPU is supported by foundational...,"The BlueField DPU supports DOCA, enabling soft...",CORRECT,"The BlueField DPU supports DOCA software, enab...",CORRECT
13,14,What does the NVIDIA GPU Cloud registry offer?,The NVIDIA GPU Cloud registry offers a compreh...,"A comprehensive catalog of easy-to-use, optimi...",CORRECT,"A comprehensive catalog of easy-to-use, optimi...",CORRECT
14,15,What are the technological features of the GeF...,The GeForce RTX 40 Series GPUs feature third g...,The GeForce RTX 40 Series GPUs feature the Ada...,CORRECT,The GeForce RTX 40 Series features the Ada Lov...,CORRECT
15,16,What generation technology does the 40 Series ...,The 40 Series graphics cards feature third gen...,"Third-generation RTX technology, third-generat...",CORRECT,Third-generation RTX technology.,INCORRECT
16,17,What capabilities are introduced by NVIDIA's G...,NVIDIA's GPU computing platform enhances produ...,New capabilities for critical workflows in fie...,CORRECT,New capabilities for critical workflows in fie...,CORRECT
17,18,What kind of applications now support RTX tech...,Many leading 3D design and content creation ap...,Leading 3D design and content creation applica...,CORRECT,Many leading 3D design and content creation ap...,CORRECT
18,19,What are some current enterprise applications ...,Current enterprise applications of VR and AR t...,Current enterprise applications include virtua...,CORRECT,"Virtual car showrooms, surgical training, arch...",CORRECT
19,20,What features does the DRIVE Software platform...,The DRIVE Software platform includes DRIVE Cha...,The DRIVE Software platform includes:\n\n- DRI...,CORRECT,The DRIVE Software platform includes:\n\n- DRI...,CORRECT
20,21,How does the company support multi-billion-dol...,The company supports multi-billion-dollar end ...,By using shared underlying technology with var...,CORRECT,By using shared underlying technology across s...,CORRECT
21,22,What comprehensive solutions does the company ...,"The company provides a complete, end-to-end ac...",The company provides an end-to-end accelerated...,CORRECT,"The company provides a complete, end-to-end ac...",CORRECT
22,23,How does the company advance autonomous vehicl...,The company provides a fully functional safety...,The company advances autonomous vehicle techno...,CORRECT,The company advances autonomous vehicle techno...,CORRECT
23,24,What specific features are used to enhance the...,The company uses its GeForce Experience to opt...,GeForce Experience enhances consumers’ gaming ...,CORRECT,GeForce Experience optimizes PC settings and e...,CORRECT
24,25,How does the company's sales and marketing str...,The global sales and marketing teams work clos...,The company’s global sales and marketing teams...,CORRECT,The strategy supports technology distribution ...,CORRECT
25,26,What is the primary role of NVIDIA's partner n...,NVIDIA's partner network is primarily involved...,"NVIDIA’s partner network helps design, test, a...",CORRECT,"Designing, testing, and qualifying system desi...",CORRECT
26,27,How does NVIDIA encourage the development of s...,NVIDIA encourages the development of software ...,NVIDIA builds developer relationships by provi...,CORRECT,NVIDIA encourages development by making its pr...,CORRECT
27,28,How does NVIDIA's product revenue typically va...,NVIDIA's product revenue typically sees strong...,Consumer product revenue is typically stronger...,CORRECT,NVIDIA’s consumer product revenue is typically...,CORRECT
28,29,What manufacturing strategy does NVIDIA employ...,NVIDIA employs a fabless manufacturing strateg...,NVIDIA employs a fabless manufacturing strateg...,CORRECT,NVIDIA employs a fabless manufacturing strateg...,CORRECT
29,30,Who are NVIDIA's primary suppliers for semicon...,NVIDIA's primary suppliers for semiconductor w...,Taiwan Semiconductor Manufacturing Company Lim...,CORRECT,Taiwan Semiconductor Manufacturing Company Lim...,CORRECT
30,31,What are the principal competitive factors in ...,The principal competitive factors include perf...,The principal competitive factors are performa...,CORRECT,The principal competitive factors are performa...,CORRECT
31,32,How does the text describe the changes expecte...,The text suggests that competition will increa...,The company expects competition to intensify f...,CORRECT,Competition is expected to increase from exist...,CORRECT
32,33,What entities are identified as significant so...,Significant sources of competition include com...,Companies providing or intending to provide:\n...,CORRECT,Companies providing or intending to provide GP...,CORRECT
33,34,What measures does the company rely on to prot...,The company relies on a combination of patents...,"The company relies on patents, trademarks, tra...",CORRECT,"The company relies on patents, trademarks, tra...",CORRECT
34,35,What recent regulatory changes have impacted t...,"During the third quarter of fiscal year 2023, ...",The U.S. government introduced new license req...,CORRECT,"During Q3 fiscal 2023, the U.S. government int...",CORRECT
35,36,What was the main reason for the termination o...,The main reason for the termination of the Sha...,Significant regulatory challenges prevented co...,CORRECT,Significant regulatory challenges preventing c...,CORRECT
36,37,What was the financial cost associated with th...,The financial cost associated with the termina...,The termination resulted in a $1.35 billion ac...,CORRECT,$1.35 billion.,CORRECT
37,38,What percentage of global electricity usage do...,"By the end of fiscal year 2025, NVIDIA aims to...",100%,CORRECT,100%,CORRECT
38,39,What new governmental requirements were announ...,"During the third quarter of fiscal year 2023, ...",New license requirements for certain exports t...,CORRECT,New U.S. government license requirements affec...,CORRECT
39,40,What is the role of the Nominating and Corpora...,The role of the Nominating and Corporate Gover...,It reviews and discusses NVIDIA’s ESG-related ...,CORRECT,The Nominating and Corporate Governance Commit...,CORRECT
40,41,How many employees did the company have at the...,"At the end of fiscal year 2023, the company ha...","The company had 26,196 employees in 35 countries.",CORRECT,"26,196 employees in 35 countries.",CORRECT
41,42,What percentage of the company's workforce hol...,About 50% of the company's workforce hold adva...,About 50%.,CORRECT,50%,CORRECT
42,43,What was the overall turnover rate at the comp...,The overall turnover rate at the company in fi...,5.3%,CORRECT,5.3%,CORRECT
43,44,What types of learning opportunities does the ...,The company provides on-the-job training progr...,The company provides on-the-job learning throu...,CORRECT,"Training programs, one-on-one coaching, ongoin...",CORRECT
44,45,What percentage of the global workforce was fe...,19%,19%,CORRECT,19%,CORRECT
45,46,What degree does Jen-Hsun Huang hold from Stan...,M.S.E.E. degree,An M.S.E.E. degree.,CORRECT,Jen-Hsun Huang holds an M.S.E.E. degree from S...,CORRECT
46,47,What is the percentage of Black or African Ame...,6%,6%,CORRECT,6%,CORRECT
47,48,What position did Colette M. Kress hold before...,Senior Vice President and Chief Financial Offi...,Senior Vice President and Chief Financial Offi...,CORRECT,Senior Vice President and Chief Financial Offi...,CORRECT
48,49,What role did Debora Shoquist hold at JDS Unip...,Debora Shoquist served as the Executive Vice P...,Executive Vice President of Operations.,CORRECT,Executive Vice President of Operations.,CORRECT
49,50,What degrees does Timothy S. Teter hold and fr...,Timothy S. Teter holds a B.S. degree in Mechan...,Timothy S. Teter holds a B.S. in Mechanical En...,CORRECT,Timothy S. Teter holds a B.S. in Mechanical En...,CORRECT

In [83]:
error_analysis = results_a[
    ["sample_id", "question", "reference_answer",
     "predicted_answer", "final_evaluation"]
].merge(
    results_b[
        ["sample_id", "predicted_answer", "final_evaluation"]
    ],
    on="sample_id",
    suffixes=("_sol", "_luna")
)

error_analysis[
    (error_analysis["final_evaluation_sol"] != "CORRECT") |
    (error_analysis["final_evaluation_luna"] != "CORRECT")
]

,sample_id,question,reference_answer,predicted_answer_sol,final_evaluation_sol,predicted_answer_luna,final_evaluation_luna
5,6,What industries use NVIDIA's GPUs and software...,NVIDIA's GPUs and software are used for automa...,"Transportation, healthcare, financial services...",INCORRECT,"Transportation, healthcare, financial services...",CORRECT
15,16,What generation technology does the 40 Series ...,The 40 Series graphics cards feature third gen...,"Third-generation RTX technology, third-generat...",CORRECT,Third-generation RTX technology.,INCORRECT

In [84]:
agreement = (
    results_a["predicted_answer"].apply(normalize_text)
    ==
    results_b["predicted_answer"].apply(normalize_text)
)

agreement_rate = agreement.mean()

print(
    f"Normalized exact agreement: "
    f"{agreement_rate * 100:.1f}%"
)

Normalized exact agreement: 28.0%